server:
  port: 8081
spring:
  profiles:
    active: dev

# 配置mybatis-plus的xml文件扫描路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# 和代码中指定的jwt前缀要一致
soft:
  jwt:
    # 加密秘钥，自己指定
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长为7天，单位是秒
    expire: 604800
    header: Authorization
